# Generated by Django 4.0 on 2023-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_remove_userprofile_user_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='', max_length=100),
        ),
    ]
