# Generated by Django 4.0 on 2023-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
